name: flutter_clean_architecture_task
description: "This project is for hiring progress of AbanTether company written by AmirAbbas Jannatian"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  #State management
  flutter_bloc: ^9.0.0

  #Dependency injection
  get_it: ^8.0.3

  #Local storage
  encrypt_shared_preferences: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
